### ISSUE TITLE
好像是验证码的问题

### ISSUE THREAD

**Issue by 1715819** [linweiyuan/java-chatgpt-api#2]
.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.5)

2023-04-07T09:32:10.930Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.Application    : Starting Application v1.0.0 using Java 17.0.6 with PID 1 (/app/build/libs/java-chatgpt-api-1.0.0.jar started by root in /app)
2023-04-07T09:32:10.941Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.Application    : No active profile set, falling back to 1 default profile: "default"
2023-04-07T09:32:14.235Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-04-07T09:32:14.265Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-04-07T09:32:14.266Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.7]
2023-04-07T09:32:14.630Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-04-07T09:32:14.635Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 3488 ms
Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set
2023-04-07T09:32:21.660Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : There's a lot of checking to do, please wait...
2023-04-07T09:32:21.661Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Access denied?
2023-04-07T09:32:24.680Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : No
2023-04-07T09:32:24.680Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : At capacity?
2023-04-07T09:32:27.686Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : No
2023-04-07T09:32:27.691Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Needs handle captcha?
2023-04-07T09:32:37.698Z ERROR 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Yes
2023-04-07T09:32:37.699Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Try to handle captcha
2023-04-07T09:32:37.712Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 1
2023-04-07T09:32:37.727Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 2
2023-04-07T09:32:37.801Z  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chatGPTController' defined in URL [jar:file:/app/build/libs/java-chatgpt-api-1.0.0.jar!/BOOT-INF/classes!/com/linweiyuan/chatgptapi/controller/ChatGPTController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'chatGPTServiceImpl' defined in URL [jar:file:/app/build/libs/java-chatgpt-api-1.0.0.jar!/BOOT-INF/classes!/com/linweiyuan/chatgptapi/service/impl/ChatGPTServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'page' defined in class path resource [com/linweiyuan/chatgptapi/config/PlaywrightConfig.class]: Failed to instantiate [com.microsoft.playwright.Page]: Factory method 'page' threw exception with message: Cannot handle captcha at this time, please restart to have a try or use API mode first.
2023-04-07T09:32:37.812Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-04-07T09:32:37.882Z  INFO 1 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-04-07T09:32:37.962Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chatGPTController' defined in URL [jar:file:/app/build/libs/java-chatgpt-api-1.0.0.jar!/BOOT-INF/classes!/com/linweiyuan/chatgptapi/controller/ChatGPTController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'chatGPTServiceImpl' defined in URL [jar:file:/app/build/libs/java-chatgpt-api-1.0.0.jar!/BOOT-INF/classes!/com/linweiyuan/chatgptapi/service/impl/ChatGPTServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'page' defined in class path resource [com/linweiyuan/chatgptapi/config/PlaywrightConfig.class]: Failed to instantiate [com.microsoft.playwright.Page]: Factory method 'page' threw exception with message: Cannot handle captcha at this time, please restart to have a try or use API mode first.
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[spring-context-6.0.7.jar!/:6.0.7]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.7.jar!/:6.0.7]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at com.linweiyuan.chatgptapi.Application.main(Application.java:11) ~[classes!/:1.0.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[java-chatgpt-api-1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[java-chatgpt-api-1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[java-chatgpt-api-1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[java-chatgpt-api-1.0.0.jar:1.0.0]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chatGPTServiceImpl' defined in URL [jar:file:/app/build/libs/java-chatgpt-api-1.0.0.jar!/BOOT-INF/classes!/com/linweiyuan/chatgptapi/service/impl/ChatGPTServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'page' defined in class path resource [com/linweiyuan/chatgptapi/config/PlaywrightConfig.class]: Failed to instantiate [com.microsoft.playwright.Page]: Factory method 'page' threw exception with message: Cannot handle captcha at this time, please restart to have a try or use API mode first.
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[spring-beans-6.0.7.jar!/:6.0.7]
        ... 27 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'page' defined in class path resource [com/linweiyuan/chatgptapi/config/PlaywrightConfig.class]: Failed to instantiate [com.microsoft.playwright.Page]: Factory method 'page' threw exception with message: Cannot handle captcha at this time, please restart to have a try or use API mode first.
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:491) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[spring-beans-6.0.7.jar!/:6.0.7]
        ... 41 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.playwright.Page]: Factory method 'page' threw exception with message: Cannot handle captcha at this time, please restart to have a try or use API mode first.
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-6.0.7.jar!/:6.0.7]
        ... 55 common frames omitted
Caused by: com.linweiyuan.chatgptapi.exception.CaptchaException: Cannot handle captcha at this time, please restart to have a try or use API mode first.
        at com.linweiyuan.chatgptapi.config.PlaywrightConfig.page(PlaywrightConfig.java:62) ~[classes!/:1.0.0]
        at com.linweiyuan.chatgptapi.config.PlaywrightConfig$$SpringCGLIB$$0.CGLIB$page$0(<generated>) ~[classes!/:1.0.0]
        at com.linweiyuan.chatgptapi.config.PlaywrightConfig$$SpringCGLIB$$2.invoke(<generated>) ~[classes!/:1.0.0]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.0.7.jar!/:6.0.7]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.0.7.jar!/:6.0.7]
        at com.linweiyuan.chatgptapi.config.PlaywrightConfig$$SpringCGLIB$$0.page(<generated>) ~[classes!/:1.0.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.7.jar!/:6.0.7]
        ... 56 common frames omitted

**Comment by linweiyuan** [comment]
看下重启这个服务能否解决

不能的话，可能换个节点试下

再不行的话可能要等等

这个问题我测试的时候是那种点完验证码后，还要点，点完还要点的场景，比较难测试

**Comment by 1715819** [comment]
期待大佬进一步更新！！

**Comment by linweiyuan** [comment]
改了改，用 `https://mvnrepository.com` 这个网站测试过，因为必弹验证码，能过

重新拉下镜像试试

**Comment by 1715819** [comment]
一直出现： 
2023-04-07T12:41:43.143Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 2
2023-04-07T12:41:43.174Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 1

完整的日志：

 .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.5)

2023-04-07T12:41:09.192Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.Application    : Starting Application v1.0.0 using Java 17.0.6 with PID 1 (/app/build/libs/java-chatgpt-api-1.0.0.jar started by root in /app)
2023-04-07T12:41:09.207Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.Application    : No active profile set, falling back to 1 default profile: "default"
2023-04-07T12:41:17.210Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-04-07T12:41:17.254Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-04-07T12:41:17.255Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.7]
2023-04-07T12:41:17.623Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-04-07T12:41:17.632Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 8010 ms
Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set
2023-04-07T12:41:26.742Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : There's a lot of checking to do, please wait...
2023-04-07T12:41:26.749Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Access denied?
2023-04-07T12:41:29.780Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : No
2023-04-07T12:41:29.780Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : At capacity?
2023-04-07T12:41:32.783Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : No
2023-04-07T12:41:32.785Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Needs handle captcha?
2023-04-07T12:41:42.788Z ERROR 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Yes
2023-04-07T12:41:42.789Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Try to handle captcha
2023-04-07T12:41:42.815Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 1
2023-04-07T12:41:42.836Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 2
2023-04-07T12:41:42.959Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 1
2023-04-07T12:41:42.995Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 2
2023-04-07T12:41:43.054Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 1
2023-04-07T12:41:43.068Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 2
2023-04-07T12:41:43.095Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 1
2023-04-07T12:41:43.104Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 2
2023-04-07T12:41:43.134Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 1
2023-04-07T12:41:43.143Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 2
2023-04-07T12:41:43.174Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Waiting for captcha phase 1

**Comment by linweiyuan** [comment]
又加了一些判断，失败自动截图，到时你上传来看看具体页面长什么样

我测试很少出现验证码，可能换个节点试试

**Comment by 1715819** [comment]
![1](https://user-images.githubusercontent.com/75056973/230690660-3fd507d7-0462-4594-a243-10cca60bb595.png)

**Comment by 1715819** [comment]
很奇怪，重启了一下机器成功了

2023-04-07T23:11:54.059Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : There's a lot of checking to do, please wait...
2023-04-07T23:11:54.063Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Access denied?
2023-04-07T23:11:57.089Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : No
2023-04-07T23:11:57.089Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : At capacity?
2023-04-07T23:12:00.091Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : No
2023-04-07T23:12:00.095Z  WARN 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Needs handle captcha?
2023-04-07T23:12:00.165Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : No
2023-04-07T23:12:00.166Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Welcome to ChatGPT
2023-04-07T23:12:04.662Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-04-07T23:12:04.708Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.Application    : Started Application in 32.803 seconds (process running for 35.359)

**Comment by linweiyuan** [comment]
我测试时，这种验证码是能点到的，不知为何在你这边会失败

这个界面就是那种正常的验证码，也没有很特别

---

确实，有时验证码出现，重启就会不用，我单纯重启 API 没有重启电脑也可以

**Comment by 1715819** [comment]
貌似又出现了新的问题，

? org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' is not supported ?

**Comment by linweiyuan** [comment]
这个单纯这样看，是使用的问题

是不是在 POST 接口上用了 GET？

前端用的是哪个项目，可以准确试出来吗？

**Comment by 1715819** [comment]
前端用的是
https://github.com/Chanzhaoyu/chatgpt-web
环境变量那儿是这样写的：https://xxxx.com/conversation

**Comment by linweiyuan** [comment]
那感觉不应该

你看下怎么试出来，能不能百分百试出来

**Comment by 1715819** [comment]
前端界面发消息之后没有任何反应


2023-04-08T02:01:01.392Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.misc.LogUtil   : Welcome to ChatGPT
2023-04-08T02:01:06.951Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-04-08T02:01:07.022Z  INFO 1 --- [           main] com.linweiyuan.chatgptapi.Application    : Started Application in 36.386 seconds (process running for 39.041)
2023-04-08T02:01:19.960Z  INFO 1 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-04-08T02:01:19.966Z  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-04-08T02:01:19.970Z  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
2023-04-08T02:01:20.066Z  INFO 1 --- [nio-8080-exec-1] com.linweiyuan.chatgptapi.misc.LogUtil   : /conversation
2023-04-08T02:01:25.752Z  INFO 1 --- [nio-8080-exec-2] com.linweiyuan.chatgptapi.misc.LogUtil   : /conversation
2023-04-08T02:01:35.692Z  INFO 1 --- [io-8080-exec-10] com.linweiyuan.chatgptapi.misc.LogUtil   : /conversation
2023-04-08T02:01:35.886Z  INFO 1 --- [nio-8080-exec-3] com.linweiyuan.chatgptapi.misc.LogUtil   : /conversation
2023-04-08T02:01:45.155Z  INFO 1 --- [nio-8080-exec-4] com.linweiyuan.chatgptapi.misc.LogUtil   : /conversation
2023-04-08T02:01:45.312Z  INFO 1 --- [nio-8080-exec-5] com.linweiyuan.chatgptapi.misc.LogUtil   : /conversation

**Comment by linweiyuan** [comment]
其实这个问题出现在 `chatgpt-web` 项目，准确说是依赖的库：https://github.com/transitive-bullshit/chatgpt-api/blob/main/src/chatgpt-unofficial-proxy-api.ts#L143-L155

你看目前 ChatGPT 官网的请求数据：

```json
{
	"action": "next",
	"messages": [{
		"id": "xxx",
		"author": {
			"role": "user"
		},
		"content": {
			"content_type": "text",
			"parts": ["hello"]
		}
	}],
	"parent_message_id": "xxx",
	"model": "text-davinci-002-render-sha",
	"timezone_offset_min": 0
}
```

而利用这个库发出的数据：

```json
{
	"parent_message_id": "xxx",
	"action": "next",
	"messages": [{
		"author": null,
		"content": {
			"content_type": "text",
			"parts": ["hello"]
		},
		"id": "xxx"
	}],
	"model": "text-davinci-002-render-sha"
}
```

`author` 里面并没有 `role` 对象

---

这个在 `go-chatgpt-api` 就正常是因为，`String` 在 Java 中会变成 null，而在 Go 中变成 ""

晚点这边出个版本适配 `chatgpt-web`

**Comment by linweiyuan** [comment]
目前正常了
