### ISSUE TITLE
今天开始绕不过去了

### ISSUE THREAD

**Issue by aloasut** [linweiyuan/java-chatgpt-api#3]
报错如下：
```
app_1                   | POST http://go-chatgpt-api:8080/conversation {
go-chatgpt-api          | INFO[0029] Welcome to ChatGPT                
go-chatgpt-api          | panic: runtime error: invalid memory address or nil pointer dereference
go-chatgpt-api          | [signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x7af788]
go-chatgpt-api          | goroutine 1 [running]:
go-chatgpt-api          | github.com/linweiyuan/go-chatgpt-api/webdriver.HandleCaptcha.func1({0x939c98, 0xc0000ea630})
go-chatgpt-api          | 	/app/webdriver/captcha.go:40 +0x68
go-chatgpt-api          | github.com/tebeka/selenium.(*remoteWD).WaitWithTimeoutAndInterval(0x40d507?, 0xc00009e228, 0xdf8475800, 0xbc7201?)
go-chatgpt-api          | 	/go/pkg/mod/github.com/tebeka/selenium@v0.9.9/remote.go:1204 +0x65
go-chatgpt-api          | github.com/tebeka/selenium.(*remoteWD).Wait(0xc00042e068?, 0xc000443a70?)
go-chatgpt-api          | 	/go/pkg/mod/github.com/tebeka/selenium@v0.9.9/remote.go:1224 +0x28
go-chatgpt-api          | github.com/linweiyuan/go-chatgpt-api/webdriver.HandleCaptcha({0x939c98?, 0xc0000ea630})
go-chatgpt-api          | 	/app/webdriver/captcha.go:33 +0x77
go-chatgpt-api          | github.com/linweiyuan/go-chatgpt-api/webdriver.init.0()
go-chatgpt-api          | 	/app/webdriver/webdriver.go:52 +0x337
go-chatgpt-api          | INFO[0035] Welcome to ChatGPT           
```

**Comment by linweiyuan** [comment]
重启也不行吗？

好像提错位置了，这个是 Java 项目。。。

**Comment by aloasut** [comment]
谢谢作者，修好了。
