### ISSUE TITLE
如何搭建在本地

### ISSUE THREAD

**Issue by Passerby1011** [linweiyuan/java-chatgpt-api#4]
如何搭建在本地，我一直使用的ACCESS_TOKEN，最近社区的反代不稳定，我想要这个项目搭建自己的反代，我是全局透明代理（openclash），想把反代搭建造nas上，用docker试了好几次均失败了，大佬能出个教程吗？
docker network create chatgpt
docker run --name cchatgpt-proxy-server-warp --restart unless-stopped --network chatgpt -e HTTP_PROXY=http://192.168.31.9:7890 -d linweiyuan/cchatgpt-proxy-server-warp
docker run --name java-chatgpt-api --restart unless-stopped --network chatgpt -e GIN_MODE=release -e PROXY=socks5://chatgpt-proxy-server-warp:65535 -e HTTP_PROXY=http://192.168.31.9:7890 -d linweiyuan/java-chatgpt-api
这是我用的参数,希望大佬能出个教程

**Comment by linweiyuan** [comment]
搭建在本地的话，`WARP` 不需要

透明代理不用额外再设置 `HTTP_PROXY`

---

这个命令即可
`docker run -d --rm -p 8080:8080 -e CHATGPT=true linweiyuan/java-chatgpt-api`

**Comment by Passerby1011** [comment]
发现了两个报错
第一个
![image](https://user-images.githubusercontent.com/63802758/232763539-0ec684e1-1059-4bab-b421-01adf7f4b6ff.png)
![image](https://user-images.githubusercontent.com/63802758/232763033-278346e9-7f50-4594-8535-4b70e13670af.png)
![image](https://user-images.githubusercontent.com/63802758/232763112-fbd13244-10e6-4075-b906-b13c22d6a991.png)
![image](https://user-images.githubusercontent.com/63802758/232763164-80778f92-265a-49c5-b60a-6943a580c659.png)
第二个是过一段时间后没反应
![image](https://user-images.githubusercontent.com/63802758/232763675-3795a492-638e-428a-8315-9eecdffeef46.png)
![image](https://user-images.githubusercontent.com/63802758/232763682-1c5ba3d5-99c8-49d8-a5ce-f2c49aa9ee23.png)

**Comment by Passerby1011** [comment]
发现了两个报错
第一个
![image](https://user-images.githubusercontent.com/63802758/232763539-0ec684e1-1059-4bab-b421-01adf7f4b6ff.png)
![image](https://user-images.githubusercontent.com/63802758/232763033-278346e9-7f50-4594-8535-4b70e13670af.png)
![image](https://user-images.githubusercontent.com/63802758/232763112-fbd13244-10e6-4075-b906-b13c22d6a991.png)
![image](https://user-images.githubusercontent.com/63802758/232763164-80778f92-265a-49c5-b60a-6943a580c659.png)
第二个是没反应
![image](https://user-images.githubusercontent.com/63802758/232763675-3795a492-638e-428a-8315-9eecdffeef46.png)
![image](https://user-images.githubusercontent.com/63802758/232763682-1c5ba3d5-99c8-49d8-a5ce-f2c49aa9ee23.png)

**Comment by linweiyuan** [comment]
第一个错好办，如果你的前端项目有处理这个异常，那么就不会出现在日志里，你看它的错误信息：
![2023-04-18_20-02](https://user-images.githubusercontent.com/49076004/232771445-39acf5d2-dd41-4144-be28-f691677f0d1c.png)

不知道你用哪个前端项目，这种错仅仅需要重新获取一遍当前对话内容，处理好那些 `parent_message_id` 即可

---

第二个错是浏览器的错，不好处理，会经常出现吗？有没有必现的步骤

**Comment by Passerby1011** [comment]
第二个错误，我就是放置一段时间后出现的，没有必现的步骤

**Comment by linweiyuan** [comment]
目前还没有好的方法解决浏览器的错

**Comment by citcon-aoyansheng** [comment]
> 搭建在本地的话，`WARP` 不需要
> 
> 透明代理不用额外再设置 `HTTP_PROXY`
> 
> 这个命令即可 `docker run -d --rm -p 8080:8080 -e CHATGPT=true linweiyuan/java-chatgpt-api`

我在mac上用这个命令一直这个错误


```
Caused by: com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://chat.openai.com/", waiting until "load"
============================================================
  name='TimeoutError
  stack='TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://chat.openai.com/", waiting until "load"
============================================================
    at ProgressController.run (/tmp/playwright-java-18120914689010442332/package/lib/server/progress.js:88:26)
    at Frame.goto (/tmp/playwright-java-18120914689010442332/package/lib/server/frames.js:520:23)
    at FrameDispatcher.goto (/tmp/playwright-java-18120914689010442332/package/lib/server/dispatchers/frameDispatcher.js:75:121)
    at DispatcherConnection.dispatch (/tmp/playwright-java-18120914689010442332/package/lib/server/dispatchers/dispatcher.js:312:46)
}
	at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:52) ~[playwright-1.32.0.jar!/:1.32.0]
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:111) ~[playwright-1.32.0.jar!/:1.32.0]
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:126) ~[playwright-1.32.0.jar!/:1.32.0]
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102) ~[playwright-1.32.0.jar!/:1.32.0]
	at com.microsoft.playwright.impl.FrameImpl.navigateImpl(FrameImpl.java:463) ~[playwright-1.32.0.jar!/:1.32.0]
	at com.microsoft.playwright.impl.PageImpl.lambda$navigate$45(PageImpl.java:853) ~[playwright-1.32.0.jar!/:1.32.0]
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47) ~[playwright-1.32.0.jar!/:1.32.0]
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87) ~[playwright-1.32.0.jar!/:1.32.0]
	at com.microsoft.playwright.impl.PageImpl.navigate(PageImpl.java:853) ~[playwright-1.32.0.jar!/:1.32.0]
	at com.microsoft.playwright.impl.PageImpl.navigate(PageImpl.java:42) ~[playwright-1.32.0.jar!/:1.32.0]
	at com.microsoft.playwright.Page.navigate(Page.java:5224) ~[playwright-1.32.0.jar!/:1.32.0]
	at com.linweiyuan.chatgptapi.config.PlaywrightConfig.page(PlaywrightConfig.java:44) ~[classes!/:1.0.0]
	at com.linweiyuan.chatgptapi.config.PlaywrightConfig$$SpringCGLIB$$0.CGLIB$page$0(<generated>) ~[classes!/:1.0.0]
	at com.linweiyuan.chatgptapi.config.PlaywrightConfig$$SpringCGLIB$$2.invoke(<generated>) ~[classes!/:1.0.0]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.0.7.jar!/:6.0.7]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.0.7.jar!/:6.0.7]
	at com.linweiyuan.chatgptapi.config.PlaywrightConfig$$SpringCGLIB$$0.page(<generated>) ~[classes!/:1.0.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.7.jar!/:6.0.7]
	... 56 common frames omitted
Caused by: com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://chat.openai.com/", waiting until "load"
============================================================
  name='TimeoutError
  stack='TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://chat.openai.com/", waiting until "load"
============================================================
    at ProgressController.run (/tmp/playwright-java-18120914689010442332/package/lib/server/progress.js:88:26)
    at Frame.goto (/tmp/playwright-java-18120914689010442332/package/lib/server/frames.js:520:23)
    at FrameDispatcher.goto (/tmp/playwright-java-18120914689010442332/package/lib/server/dispatchers/frameDispatcher.js:75:121)
    at DispatcherConnection.dispatch (/tmp/playwright-java-18120914689010442332/package/lib/server/dispatchers/dispatcher.js:312:46)
}
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:224) ~[playwright-1.32.0.jar!/:1.32.0]
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:206) ~[playwright-1.32.0.jar!/:1.32.0]
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109) ~[playwright-1.32.0.jar!/:1.32.0]
	... 76 common frames omitted



```

**Comment by linweiyuan** [comment]
需要科学上网，在 `mac` 上执行 `curl -v https://chat.openai.com` 是卡住还是有返回？

在容器里执行又是怎么效果？

透明代理如果是 `tproxy` 不支持 `docker`，`redirect` 才支持

**Comment by citcon-aoyansheng** [comment]
容器了执行部了curl，本机执行好像卡住了
*   Trying 31.13.95.48:443...
* connect to 31.13.95.48 port 443 failed: Operation timed out
* Failed to connect to chat.openai.com port 443 after 75486 ms: Couldn't connect to server
* Closing connection 0
curl: (28) Failed to connect to chat.openai.com port 443 after 75486 ms: Couldn't connect to server

**Comment by linweiyuan** [comment]
就是网络没弄好，要在这个基础上通了，`api` 才能正常工作

容器里安装 `curl`：`apk add curl`

**Comment by citcon-aoyansheng** [comment]
我是本地本子，通过ShadowsocksX-NG 这个工具加的梯子，但是浏览器能打开那个网址就直接进官网ChatGPT了，奇怪了刚刚没出现让我验证的东西，就直接能发消息

**Comment by Passerby1011** [comment]
这个项目有bug，我go-chatgpt-api用着挺稳定的

**Comment by citcon-aoyansheng** [comment]
go-chatgpt-api 的我也报错，
	if WebDriver == nil { // 这里出现空
		logger.Error("Please make sure chatgpt proxy service is running")
		return
	}

**Comment by Passerby1011** [comment]
![image](https://user-images.githubusercontent.com/63802758/233149852-5640cc6c-4e94-46b2-9a80-266cacddaa8c.png)

**Comment by linweiyuan** [comment]
> go-chatgpt-api 的我也报错， if WebDriver == nil { // 这里出现空 logger.Error("Please make sure chatgpt proxy service is running") return }

如果是容器跑，空的话，是那个 `chatgpt-proxy-server` 有可能挂了，这个挂了后 `api` 就用不了

但是你本地跑出现空，因为本地跑也要 `driver`，要么连接容器，然后用 `headless` 模式，不然就是空

要么本地单独跑 `driver`，这样 `headless` 模式也可以取消

可以参考 `README` 第二篇文章的视频，`07:56` 开始是 `go-chatgpt-api`

**Comment by linweiyuan** [comment]
> 这个项目有bug，我go-chatgpt-api用着挺稳定的

`go-chatgpt-api` 也有很多 `bug`，但是有些是外套浏览器导致的很难搞

总之有一个能跑就行

**Comment by citcon-aoyansheng** [comment]
> > go-chatgpt-api 的我也报错， if WebDriver == nil { // 这里出现空 logger.Error("Please make sure chatgpt proxy service is running") return }
> 
> 如果是容器跑，空的话，是那个 `chatgpt-proxy-server` 有可能挂了，这个挂了后 `api` 就用不了
> 
> 但是你本地跑出现空，因为本地跑也要 `driver`，要么连接容器，然后用 `headless` 模式，不然就是空
> 
> 要么本地单独跑 `driver`，这样 `headless` 模式也可以取消
> 
> 可以参考 `README` 第二篇文章的视频，`07:56` 开始是 `go-chatgpt-api`

我先是本机容器里跑的出现了空，但是看了proxy-server的那个log显示运行成功，没有任何错误

然后源码本地再跑打断点看了还是有空情况，然就来找这个java的来试了。我感觉可能我本地的梯子没弄好，我本地的代理地址是http://127.0.0.1:1087 ，但是这个容器要怎么弄来着弄了半天没弄好

**Comment by linweiyuan** [comment]
我刚重新推送了 `chatgpt-proxy-server`，开启了啰嗦模式，试下重拉这个看输出什么

**Comment by citcon-aoyansheng** [comment]
昨晚我用java的api可以连上了，早上试了下就是速度有点慢，
![image](https://user-images.githubusercontent.com/96765372/233238377-d6973bfd-0afc-45dc-bc15-80fbd1811185.png)

![image](https://user-images.githubusercontent.com/96765372/233238447-fa47fcf4-a79c-407b-9c2b-5f24cc05299b.png)

配置是这个

  ```
java-chatgpt-api:
    container_name: java-chatgpt-api
    image: linweiyuan/java-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - CHATGPT=true
      # - PROXY=socks5://chatgpt-proxy-server-warp:65535
      - http_proxy=http://host.docker.internal:1087
      - https_proxy=http://host.docker.internal:1087
    restart: unless-stopped
```

**Comment by linweiyuan** [comment]
有理由相信是 ChatGPT 回复慢

程序只是转发一下

用旁边 go 那个试试慢不慢

**Comment by citcon-aoyansheng** [comment]
chatgpt-proxy-server

`
[1681996776.260][DEBUG]: DevTools HTTP Request: http://localhost:45435/json/list
[577:577:0420/131936.320237:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[577:649:0420/131936.320795:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[577:649:0420/131936.321048:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[577:649:0420/131936.322837:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[577:649:0420/131936.323116:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[577:649:0420/131936.323286:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[577:577:0420/131936.336180:ERROR:network_service_instance_impl.cc(541)] Network service crashed, restarting service.
qemu: unknown option 'type=utility'
[1681996776.367][DEBUG]: DevTools HTTP Response: [  ]

[577:577:0420/131936.384135:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[577:577:0420/131936.396164:ERROR:network_service_instance_impl.cc(541)] Network service crashed, restarting service.
qemu: unknown option 'type=utility'
[1681996776.417][DEBUG]: DevTools HTTP Request: http://localhost:45435/json/list
[577:577:0420/131936.426441:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[577:577:0420/131936.439108:ERROR:network_service_instance_impl.cc(541)] Network service crashed, restarting service.
[577:577:0420/131936.449353:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[1681996776.452][DEBUG]: DevTools HTTP Response: [  ]

qemu: unknown option 'type=utility'
[577:577:0420/131936.456955:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[577:577:0420/131936.457097:FATAL:gpu_data_manager_impl_private.cc(440)] GPU process isn't usable. Goodbye.
[0420/131936.460071:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
qemu: uncaught target signal 6 (Aborted) - core dumped
[1681996776.502][DEBUG]: DevTools HTTP Request: http://localhost:45435/json/list
[1681996776.505][DEBUG]: DevTools HTTP Request failed
[1681996777.181][INFO]: [58d3e63a2a750cf1e92fabd21b6fbe8c] RESPONSE InitSession ERROR unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[1681996777.181][DEBUG]: Log type 'driver' lost 0 entries on destruction
[1681996777.181][DEBUG]: Log type 'browser' lost 0 entries on destruction
[1681996837.802][INFO]: [267d200061fd40a16f92018f7b7973f9] COMMAND InitSession {
   "capabilities": {
      "alwaysMatch": {
      }
   },
   "desiredCapabilities": {
      "chromeOptions": {
         "args": [ "--no-sandbox", "--disable-gpu", "--disable-dev-shm-usage", "--disable-blink-features=AutomationControlled", "--headless=new", "--proxy-server=socks5://chatgpt-proxy-server-warp:65535" ],
         "excludeSwitches": [ "enable-automation" ],
         "w3c": false
      }
   }
}
[1681996837.803][INFO]: Populating Preferences file: {
   "alternate_error_pages": {
      "enabled": false
   },
   "autofill": {
      "enabled": false
   },
   "browser": {
      "check_default_browser": false
   },
   "distribution": {
      "import_bookmarks": false,
      "import_history": false,
      "import_search_engine": false,
      "make_chrome_default_for_user": false,
      "skip_first_run_ui": true
   },
   "dns_prefetching": {
      "enabled": false
   },
   "profile": {
      "content_settings": {
         "pattern_pairs": {
            "https://*,*": {
               "media-stream": {
                  "audio": "Default",
                  "video": "Default"
               }
            }
         }
      },
      "default_content_setting_values": {
         "geolocation": 1
      },
      "default_content_settings": {
         "geolocation": 1,
         "mouselock": 1,
         "notifications": 1,
         "popups": 1,
         "ppapi-broker": 1
      },
      "password_manager_enabled": false
   },
   "safebrowsing": {
      "enabled": false
   },
   "search": {
      "suggest_enabled": false
   },
   "translate": {
      "enabled": false
   }
}
[1681996837.804][INFO]: Populating Local State file: {
   "background_mode": {
      "enabled": false
   },
   "ssl": {
      "rev_checking": {
         "enabled": false
      }
   }
}
[1681996837.804][INFO]: Launching chrome: /opt/google/chrome/google-chrome --allow-pre-commit-input --disable-background-networking --disable-blink-features=AutomationControlled --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-gpu --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-blink-features=ShadowDOMV0 --enable-logging --headless=new --log-level=0 --no-first-run --no-sandbox --no-service-autorun --password-store=basic --proxy-server=socks5://chatgpt-proxy-server-warp:65535 --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.com.google.Chrome.guMUJ8 data:,
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[696:696:0420/132039.457922:ERROR:nacl_fork_delegate_linux.cc(313)] Bad NaCl helper startup ack (0 bytes)
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[661:661:0420/132039.510300:ERROR:browser_dm_token_storage_linux.cc(100)] Error: /etc/machine-id contains 0 characters (32 were expected).
[661:706:0420/132039.591557:ERROR:file_path_watcher_inotify.cc(315)] inotify_init() failed: Function not implemented (38)
[661:707:0420/132039.604321:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[661:711:0420/132039.698802:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[661:711:0420/132039.699923:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[661:707:0420/132039.772209:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[661:707:0420/132039.773469:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
qemu: unknown option 'type=utility'
[661:707:0420/132040.099366:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[661:707:0420/132040.099748:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

DevTools listening on ws://127.0.0.1:34249/devtools/browser/c5be71f7-43ce-400c-81e8-ed675ed1db78
[1681996840.721][DEBUG]: DevTools HTTP Request: http://localhost:34249/json/version
[661:661:0420/132041.217917:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[661:661:0420/132041.230614:ERROR:network_service_instance_impl.cc(541)] Network service crashed, restarting service.
qemu: unknown option 'type=utility'
[1681996841.326][DEBUG]: DevTools HTTP Response: {
   "Browser": "Chrome/112.0.5615.121",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
   "V8-Version": "11.2.214.14",
   "WebKit-Version": "537.36 (@39cc4e45904ae9f1741c4fbaa866e629c96f2268)",
   "webSocketDebuggerUrl": "ws://localhost:34249/devtools/browser/c5be71f7-43ce-400c-81e8-ed675ed1db78"
}

[1681996841.326][DEBUG]: DevTools HTTP Request: http://localhost:34249/json/list
[661:661:0420/132041.387110:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[661:733:0420/132041.387476:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[661:733:0420/132041.387935:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[661:733:0420/132041.389543:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[661:733:0420/132041.390130:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[661:733:0420/132041.390447:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[661:661:0420/132041.402302:ERROR:network_service_instance_impl.cc(541)] Network service crashed, restarting service.
qemu: unknown option 'type=utility'
[1681996841.432][DEBUG]: DevTools HTTP Response: [  ]

[661:661:0420/132041.447162:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[661:661:0420/132041.459317:ERROR:network_service_instance_impl.cc(541)] Network service crashed, restarting service.
qemu: unknown option 'type=utility'
[1681996841.482][DEBUG]: DevTools HTTP Request: http://localhost:34249/json/list
[661:661:0420/132041.488038:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[661:661:0420/132041.500300:ERROR:network_service_instance_impl.cc(541)] Network service crashed, restarting service.
[661:661:0420/132041.508804:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[1681996841.514][DEBUG]: DevTools HTTP Response: [  ]

qemu: unknown option 'type=utility'
[661:661:0420/132041.517586:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[661:661:0420/132041.517747:FATAL:gpu_data_manager_impl_private.cc(440)] GPU process isn't usable. Goodbye.
[0420/132041.521383:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
qemu: uncaught target signal 6 (Aborted) - core dumped
[1681996841.564][DEBUG]: DevTools HTTP Request: http://localhost:34249/json/list
[1681996841.567][DEBUG]: DevTools HTTP Request failed
[1681996842.242][INFO]: [267d200061fd40a16f92018f7b7973f9] RESPONSE InitSession ERROR unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[1681996842.242][DEBUG]: Log type 'driver' lost 0 entries on destruction
[1681996842.242][DEBUG]: Log type 'browser' lost 0 entries on destruction

`

go-chatgpt-api

`
ERRO[0004] Please make sure chatgpt proxy service is running 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x7af98b]

goroutine 50 [running]:
github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh.func1()
	/app/webdriver/refresh.go:12 +0x2b
created by github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh
	/app/webdriver/refresh.go:11 +0x6a
ERRO[0004] Please make sure chatgpt proxy service is running 

`

**Comment by linweiyuan** [comment]
Java 项目？

Java 不用 proxy server

**Comment by citcon-aoyansheng** [comment]
java能通，现在试的是go的那个

**Comment by linweiyuan** [comment]
看错了，是 Go

但是提错地方了

是怎么跑的，好像看到个 qemu

**Comment by citcon-aoyansheng** [comment]
好的我贴到隔壁去
